name: CICD when merge

on:
  pull_request:
    branches: [ "main" ]

env:
  PACKER_LOG: 1
  DB_USER: root
  DB_PASSWORD: root
  RESTORE: .test.sql

jobs:
  integration_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Initialize MySQL
      run: sudo systemctl start mysql.service

    - name: Boost user
      run: |
          mysql -e "ALTER USER '${{ env.DB_USER }}'@'localhost' \
          IDENTIFIED WITH mysql_native_password BY 'root';" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - name: Create database
      run: |
          mysql -e "CREATE DATABASE assignment;" \
          -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}

    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    #- run: npm ci
    #- run: npm test

  packer_build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          packer_version: '1.9.4'

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-1

      - name: Packer init
        run: packer init aws-debian.pkr.hcl

      - name: Packer build
        run: packer build aws-debian.pkr.hcl