name: Packer Check

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  packer_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@v2
        with:
          packer_version: '1.9.4'

      - name: Packer fmt
        run: packer fmt aws-debian.pkr.hcl
        continue-on-error: true

      - name: Packer validate
        run: packer validate aws-debian.pkr.hcl

      - name: Check Workflow Outcome
        run: exit $(( ${{ steps['Packer fmt'].conclusion }} + ${{ steps['Packer validate'].conclusion }} ))